### ISSUE TITLE
Support OrbitDB/SkyBase

### ISSUE THREAD

**Issue by TheRook** [owlmessenger/owl#8]
What would you like to be added:
Consider using https://github.com/berty/go-orbit-db as a backend to expose owl as a Kademlia service. Kademlia implemented with libp2p is one of the most mature p2p networks, designed over 20 years ago it has scaled up to hundreds of millions of nodes and is the network behind Ethereum, IPFS and Magnet BitTorrent links.

Why is this needed:
It allows owl to be run as a federated dapp and hosted by a community.
https://www.youtube.com/watch?v=cC-tXnMyiBc

https://github.com/artflake/SkyBase

**Comment by brendoncarroll** [comment]
Owl uses INET256 for connecting to peers; that is not going to change.  If you wanted to make an INET256 network powered by Kademlia and libp2p, then you could configure Owl to use that by setting the `INET256_API` environment variable to point to your implementation.

INET256 has a [spec](https://github.com/inet256/inet256/blob/master/doc/10_Spec.md) and 2 implementations: [mesh256](https://github.com/inet256/inet256/tree/master/pkg/mesh256) and [diet256](https://github.com/inet256/diet256).

**Comment by TheRook** [comment]
We will avoid that mistake by not taking your suggestion.
